# Generated by Django 4.2.24 on 2025-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityInfo',
            fields=[
                ('security_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('security_name', models.CharField(max_length=100)),
                ('listing_board', models.CharField(max_length=50)),
                ('industry_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'security_info',
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.CharField(max_length=20)),
                ('report_period', models.DateField()),
                ('parent_equity_attributable', models.BigIntegerField()),
                ('net_profit_parent_chareholders', models.BigIntegerField()),
            ],
            options={
                'db_table': 'financial_report',
                'indexes': [models.Index(fields=['security_code', 'report_period'], name='financial_r_securit_ada077_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClosingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.CharField(max_length=20)),
                ('total_share_capital', models.BigIntegerField()),
                ('trade_date', models.DateField()),
                ('closing_price', models.FloatField()),
                ('EntryID', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'closing_price',
                'indexes': [models.Index(fields=['security_code', 'trade_date'], name='closing_pri_securit_353e55_idx')],
            },
        ),
    ]
